apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: compliance-mapping-service
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "26m"
spec:
  rules:
    - host: compliance-mapping.example.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: compliance-mapping-service
                port:
                  number: 80
